### ISSUE TITLE
NPE when creating 'Copyright'

### ISSUE THREAD

**Issue by jenetics** [jenetics/jpx#15]
When creating a `Copyright` object with a `null` license URL string an NPE is thrown.

```
java.lang.NullPointerException
	at java.net.URI$Parser.parse(URI.java:3042)
	at java.net.URI.<init>(URI.java:588)
	at io.jenetics.jpx.Copyright.of(Copyright.java:175)
...
```

**Comment by jenetics** [comment]
Merged into release branch 'r1.0.1'.
