### ISSUE TITLE
Line break after datetime values causes Exception

### ISSUE THREAD

**Issue by NopMap** [jenetics/jpx#86]
Loading a GPX with the following metadata 

```
<metadata>
<time>2019-07-14T10:23:24+02:00
</time>
</metadata>
<trk>
```
causes the exception:
```
Caused by: java.lang.IllegalArgumentException: Can't parse time: 2019-07-14T10:23:24+02:00
'
	at io.jenetics.jpx.ZonedDateTimeFormat.lambda$parse$4(ZonedDateTimeFormat.java:134)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.jenetics.jpx.ZonedDateTimeFormat.parse(ZonedDateTimeFormat.java:132)
	at io.jenetics.jpx.XMLReader$1.read(XMLReader.java:142)
```

If you remove the line break so the closing tag is in the same line it loads: 
```
<metadata>
<time>2019-07-14T10:23:24+02:00</time>
</metadata>
<trk>
```

**Comment by jenetics** [comment]
Merged into r1.5.2 branch.

**Comment by NopMap** [comment]
Fix confirmed.
